=== UrosOgrizovic/XML_siit_2019_2020/paperpublish/src/main/resources/data/User.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:Users="http://localhost:8080/Users"
    targetNamespace="http://localhost:8080/Users" elementFormDefault="qualified">

    <xs:element name="Users">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Users:User" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="userName">
            <xs:selector xpath="Users:User/Users:UserName"/>
            <xs:field xpath="."/>
        </xs:unique>
        
        <xs:unique name="email">
            <xs:selector xpath="Users:User/Users:EMail"/>
            <xs:field xpath="."/>
        </xs:unique>
    </xs:element>

    <xs:element name="User">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="UserName">
                    <xs:simpleType>
                        <xs:restriction base="xs:string"/>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Password" type="xs:string"/>
                <xs:element name="FullName" type="xs:string"/>
                <xs:element name="Institution" type="xs:string"/>
                <xs:element name="EMail">
                    <xs:simpleType>
                        <xs:restriction base="xs:string"/>
                    </xs:simpleType>
                </xs:element>
                <xs:element ref="Users:Roles"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Roles">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Role" default="ROLE_USER" minOccurs="1" maxOccurs="unbounded">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="ROLE_USER"/>
                            <xs:enumeration value="ROLE_EDITOR"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>

        <xs:unique name="role">
            <xs:selector xpath="Users:Role"/>
            <xs:field xpath="."/>
        </xs:unique>
    </xs:element>
</xs:schema>

=== UrosOgrizovic/XML_siit_2019_2020/paperpublish/src/main/resources/data/Users.xml
<?xml version="1.0" encoding="UTF-8"?>
<user:Users xmlns="http://www.w3.org/ns/rdfa#" 
    xmlns:user="http://localhost:8080/Users"
    xmlns:pred="http://localhost:8080/Users/predicate/"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://localhost:8080/Users file:/D:/FAKS/7.semestar/xml/projekat/User.xsd">
    <user:User about="http://localhost:8080/Users/user">
        <user:UserName  property="pred:username" datatype="xs:string">user</user:UserName>
        <user:Password>$2a$04$Vbug2lwwJGrvUXTj6z7ff.97IzVBkrJ1XfApfGNl.Z695zqcnPYra</user:Password>
        <user:FullName>User One</user:FullName>
        <user:Institution>Ns UNS</user:Institution>
        <user:EMail property="pred:email" datatype="xs:string">EMail0</user:EMail>
        <user:Roles>
            <user:Role>ROLE_USER</user:Role>
        </user:Roles>
    </user:User>
    <user:User about="http://localhost:8080/Users/admin">
        <user:UserName property="pred:username" datatype="xs:string">admin</user:UserName>
        <user:Password>$2a$04$Vbug2lwwJGrvUXTj6z7ff.97IzVBkrJ1XfApfGNl.Z695zqcnPYra</user:Password>
        <user:FullName>Editor</user:FullName>
        <user:Institution>NS UNS</user:Institution>
        <user:EMail property="pred:email" datatype="xs:string">EMail1</user:EMail>
        <user:Roles>
            <user:Role>ROLE_EDITOR</user:Role>
        </user:Roles>
    </user:User>
</user:Users>
